const provinceData = [
  {
    nombre_completo: 'Provincia de Buenos Aires',
    iso_id: 'AR-B',
    nombre: 'Buenos Aires',
    id: '06',
    iso_nombre: 'BUENOS AIRES',
  },
  {
    nombre_completo: 'Ciudad Autónoma de Buenos Aires',
    iso_id: 'AR-C',
    nombre: 'Ciudad Autónoma de Buenos Aires',
    id: '02',

    iso_nombre: 'CAPITAL FEDERAL',
  },
  {
    nombre_completo: 'Provincia de Catamarca',
    iso_id: 'AR-K',
    nombre: 'Catamarca',
    id: '10',
    iso_nombre: 'CATAMARCA',
  },
  {
    nombre_completo: 'Provincia del Chaco',
    iso_id: 'AR-H',
    nombre: 'Chaco',
    id: '22',
    iso_nombre: 'CHACO',
  },
  {
    nombre_completo: 'Provincia del Chubut',
    iso_id: 'AR-U',
    nombre: 'Chubut',
    id: '26',
    iso_nombre: 'CHUBUT',
  },
  {
    nombre_completo: 'Provincia de Córdoba',
    iso_id: 'AR-X',
    nombre: 'Córdoba',
    id: '14',
    iso_nombre: 'CORDOBA',
  },
  {
    nombre_completo: 'Provincia de Corrientes',
    iso_id: 'AR-W',
    nombre: 'Corrientes',
    id: '18',
    iso_nombre: 'CORRIENTES',
  },
  {
    nombre_completo: 'Provincia de Entre Ríos',
    iso_id: 'AR-E',
    nombre: 'Entre Ríos',
    id: '30',
    iso_nombre: 'ENTRE RIOS',
  },
  {
    nombre_completo: 'Provincia de Formosa',
    iso_id: 'AR-P',
    nombre: 'Formosa',
    id: '34',
    iso_nombre: 'FORMOSA',
  },
  {
    nombre_completo: 'Provincia de Jujuy',
    iso_id: 'AR-Y',
    nombre: 'Jujuy',
    id: '38',
    iso_nombre: 'JUJUY',
  },
  {
    nombre_completo: 'Provincia de La Pampa',
    iso_id: 'AR-L',
    nombre: 'La Pampa',
    id: '42',
    iso_nombre: 'LA PAMPA',
  },
  {
    nombre_completo: 'Provincia de La Rioja',
    iso_id: 'AR-F',
    nombre: 'La Rioja',
    id: '46',
    iso_nombre: 'LA RIOJA',
  },
  {
    nombre_completo: 'Provincia de Mendoza',
    iso_id: 'AR-M',
    nombre: 'Mendoza',
    id: '50',
    iso_nombre: 'MENDOZA',
  },
  {
    nombre_completo: 'Provincia de Misiones',
    iso_id: 'AR-N',
    nombre: 'Misiones',
    id: '54',
    iso_nombre: 'MISIONES',
  },
  {
    nombre_completo: 'Provincia del Neuquén',
    iso_id: 'AR-Q',
    nombre: 'Neuquén',
    id: '58',
    iso_nombre: 'NEUQUEN',
  },
  {
    nombre_completo: 'Provincia de Río Negro',
    iso_id: 'AR-R',
    nombre: 'Río Negro',
    id: '62',
    iso_nombre: 'RIO NEGRO',
  },
  {
    nombre_completo: 'Provincia de Salta',
    iso_id: 'AR-A',
    nombre: 'Salta',
    id: '66',
    iso_nombre: 'SALTA',
  },
  {
    nombre_completo: 'Provincia de San Juan',
    iso_id: 'AR-J',
    nombre: 'San Juan',
    id: '70',
    iso_nombre: 'SAN JUAN',
  },
  {
    nombre_completo: 'Provincia de San Luis',
    iso_id: 'AR-D',
    nombre: 'San Luis',
    id: '74',
    iso_nombre: 'SAN LUIS',
  },
  {
    nombre_completo: 'Provincia de Santa Cruz',
    iso_id: 'AR-Z',
    nombre: 'Santa Cruz',
    id: '78',
    iso_nombre: 'SANTA CRUZ',
  },
  {
    nombre_completo: 'Provincia de Santa Fe',
    iso_id: 'AR-S',
    nombre: 'Santa Fe',
    id: '82',
    iso_nombre: 'SANTA FE',
  },
  {
    nombre_completo: 'Provincia de Santiago del Estero',
    iso_id: 'AR-G',
    nombre: 'Santiago del Estero',
    id: '86',
    iso_nombre: 'SANTIAGO DEL ESTERO',
  },
  {
    nombre_completo: 'Provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur',
    iso_id: 'AR-V',
    nombre: 'Tierra del Fuego, Antártida e Islas del Atlántico Sur',
    id: '94',
    iso_nombre: 'TIERRA DEL FUEGO',
  },
  {
    nombre_completo: 'Provincia de Tucumán',
    iso_id: 'AR-T',
    nombre: 'Tucumán',
    id: '90',
    iso_nombre: 'TUCUMAN',
  },
];

export default provinceData;
